name: Docker

on: [push]

jobs:
  build:
    name: Docker - ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: docker build --tag=mocc .
        run: docker build --tag=mocc .

      - name: docker run --rm mocc make test
        run: docker run --rm mocc make test
