name: Lint

on: [push]

jobs:
  format:
    name: Format - ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: "."
          extensions: "c,h"
          clangFormatVersion: 9
