name: Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-gcc
          - ubuntu-clang
          - macOS-clang
        build-type:
          - debug
          - release
        include:
          - target: ubuntu-gcc
            os: ubuntu-latest
            cc: gcc
          - target: ubuntu-clang
            os: ubuntu-latest
            cc: clang
          - target: macOS-clang
            os: macOS-latest
            cc: clang

    name: Build ${{ matrix.build-type }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: ${{ matrix.cc }} -v
        run: ${{ matrix.cc }} -v
      - name: make test CC=${{ matrix.cc }} BUILD_TYPE=${{ matrix.build-type }}
        run: make test CC=${{ matrix.cc }} BUILD_TYPE=${{ matrix.build-type }}
